export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';

export const CHANGE_VALUE = 'CHANGE_VALUE';
export const TICK_SUBCATEGORY_VALUE = 'TICK_SUBCATEGORY_VALUE';
export const SUBMIT_ENTRY = 'SUBMIT_ENTRY';
export const SUBMIT_ENTRY_SUCCESS = 'SUBMIT_ENTRY_SUCCESS';
export const SUBMIT_ENTRY_FAIL = 'SUBMIT_ENTRY_FAIL';