export const GET_INPUTS_FROM_DATA = 'GET_INPUTS_FROM_DATA';

export const GET_ENTRIES_INIT = 'GET_ENTRIES_INIT'
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS'
export const GET_ENTRIES_FAIL = 'GET_ENTRIES_FAIL'

export const CHANGE_VALUE = 'CHANGE_VALUE';
export const TICK_SUBCATEGORY_VALUE = 'TICK_SUBCATEGORY_VALUE';

export const SUBMIT_ENTRY = 'SUBMIT_ENTRY';
export const SUBMIT_ENTRY_SUCCESS = 'SUBMIT_ENTRY_SUCCESS';
export const SUBMIT_ENTRY_FAIL = 'SUBMIT_ENTRY_FAIL';

export const ADD_TAG = 'ADD_TAG';